title: Forgotten Library Codex
description: An interactive codex for the Forgotten Library.
remote_theme: pages-themes/midnight@v0.2.0
markdown: kramdown

collections:
  pages:
    output: true
    permalink: /forgotten-library-codex/:path/
