title: Forgotten Library Codex
description: A classified archive for the Forgotten Library.
markdown: kramdown
baseurl: "/forgotten-library-codex"
collections:
  workers:
    output: true
    permalink: /forgotten-library-codex/workers/:path/
  anomalies:
    output: true
    permalink: /forgotten-library-codex/anomalies/:path/
