title: Forgotten Library Codex
description: An interactive codex for the Forgotten Library.
theme: minima
markdown: kramdown

collections:
  pages:
    output: true
    permalink: /forgotten-library-codex/:path/
