title: Forgotten Library Codex
description: A classified archive for the Forgotten Library.
markdown: kramdown
collections:
  workers:
    output: true
    permalink: /workers/:path/
  anomalies:
    output: true
    permalink: /anomalies/:path/
